### ISSUE TITLE
oc.request element issue

### ISSUE THREAD

**Issue by pittss** [octobercms/ajax#11]
Does not work
```
// Serialize an element with the request
oc.request('.some-element', 'onSomething', { data: someVar });
```
(error: Uncaught TypeError: element.matches is not a function)

Work
```
oc.request(document.querySelector('.some-element'), 'onSomething', { data: someVar });
```

OctoberCMS Version: 3.0.60

**Comment by samgeorges** [comment]
This is likely caused by 4f531e89ed047fb714dc43f0ebe5f600729bcdaf

Will take a look, thanks

**Comment by samgeorges** [comment]
Fixed by 20df7eeef09c2efd0e2f5d3293e51db7cb7c2a58
